# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'heartdi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1077, 607)
        Form.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(16, 40, 911, 51))
        self.label.setStyleSheet("color: rgb(170, 170, 0);\n"
"font: 75 26pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 71, 31))
        self.label_2.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 200, 71, 41))
        self.label_3.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 141, 31))
        self.label_4.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 320, 191, 31))
        self.label_5.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(440, 140, 111, 31))
        self.label_6.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(340, 200, 211, 41))
        self.label_7.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(370, 260, 191, 41))
        self.label_8.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(50, 370, 151, 41))
        self.label_9.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(430, 320, 121, 31))
        self.label_10.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(450, 370, 101, 31))
        self.label_11.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(800, 140, 91, 31))
        self.label_12.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(810, 200, 91, 31))
        self.label_13.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(830, 260, 71, 31))
        self.label_14.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(760, 310, 131, 31))
        self.label_15.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(780, 370, 131, 41))
        self.label_16.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(190, 500, 171, 61))
        self.pushButton.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);\n"
"color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(530, 510, 431, 41))
        self.label_17.setStyleSheet("color: rgb(170, 0, 127);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 150, 141, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 210, 141, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 260, 141, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 320, 121, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 380, 131, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(562, 139, 131, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(560, 200, 131, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(560, 270, 131, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(562, 330, 131, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(560, 380, 131, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(890, 140, 121, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(900, 200, 113, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(900, 259, 113, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(900, 310, 113, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(900, 380, 113, 31))
        self.lineEdit_15.setObjectName("lineEdit_15")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", " Prediction Whether A Person Get A Heart Disease Or Not"))
        self.label_2.setText(_translate("Form", "Male:"))
        self.label_3.setText(_translate("Form", "Age:"))
        self.label_4.setText(_translate("Form", "Education:"))
        self.label_5.setText(_translate("Form", "currentSmoker:"))
        self.label_6.setText(_translate("Form", "BPMeds:"))
        self.label_7.setText(_translate("Form", "prevalentStroke:"))
        self.label_8.setText(_translate("Form", "prevalentHyp:"))
        self.label_9.setText(_translate("Form", "cigsPerDay:"))
        self.label_10.setText(_translate("Form", "diabetes:"))
        self.label_11.setText(_translate("Form", "totChol:"))
        self.label_12.setText(_translate("Form", "sysBP:"))
        self.label_13.setText(_translate("Form", "diaBP:"))
        self.label_14.setText(_translate("Form", "BMI:"))
        self.label_15.setText(_translate("Form", "heartRate:"))
        self.label_16.setText(_translate("Form", " glucose:"))
        self.pushButton.setText(_translate("Form", "Predict"))
        self.label_17.setText(_translate("Form", "Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
